### ISSUE TITLE
Does it print to stdout ?

### ISSUE THREAD

**Issue by TrevCan** [ArianKG/KGScript#4]
I tried testing the language. Compiled it, go no errors and tried it with `./KGScript test.kgs` but did not get errors or anything at all printed to stdout.

- test.kgs
```
printi(15)
system("ls")
```

**Comment by ArianKG** [comment]
This is not working, because there are multiple lines and this is a bug.

**Comment by TrevCan** [comment]
I tired with only one command and still did not work, I’m running on Arch Linux, any suggestions?

**Comment by ArianKG** [comment]
@TrevCan Make sure there is no '\n' character at the end of file.

**Comment by ArianKG** [comment]
The problem fixed

**Comment by TrevCan** [comment]
@ArianKG great, thanks. It now works
